### ISSUE TITLE
Debug why debug log are being displayed on console while using monowrap

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Niraj-Kamdar/monowrap#5]
```
❯ npx @wraplib/pwr echo
[
  Uri {
    _config: { uri: 'wrap://pwr/echo', authority: 'pwr', path: 'echo' }
  },
  Uri {
    _config: {
      uri: 'wrap://ens/wrap-echo.eth',
      authority: 'ens',
      path: 'wrap-echo.eth'
    }
  },
  Uri {
    _config: {
      uri: 'wrap://ens-contenthash/0xe30101701220f1a92d3513fd5b90ef83f17f68f796d0b97754b528f06d90ac86c19bebeb4f76',
      authority: 'ens-contenthash',
      path: '0xe30101701220f1a92d3513fd5b90ef83f17f68f796d0b97754b528f06d90ac86c19bebeb4f76'
    }
  },
  Uri {
    _config: {
      uri: 'wrap://ipfs/QmebzauKAXoYbywLAYdBvKyPhWsDoHfkUC4wffWvjighKT',
      authority: 'ipfs',
      path: 'QmebzauKAXoYbywLAYdBvKyPhWsDoHfkUC4wffWvjighKT'
    }
  },
  Uri {
    _config: {
      uri: 'wrap://file//Users/niraj/Library/Preferences/polywrap/cache/wrappers/ipfs/QmebzauKAXoYbywLAYdBvKyPhWsDoHfkUC4wffWvjighKT',
      authority: 'file',
      path: '/Users/niraj/Library/Preferences/polywrap/cache/wrappers/ipfs/QmebzauKAXoYbywLAYdBvKyPhWsDoHfkUC4wffWvjighKT'
    }
  }
]
Invoked
Error: WasmWrapper: Wasm module aborted execution.
URI: wrap://pwr/echo
Method: main
Args: {
  "0": 129,
  "1": 164,
  "2": 97,
  "3": 114,
  "4": 103,
  "5": 115,
  "6": 144
}
Message: __wrap_abort: called `Result::unwrap()` on an `Err` value: "ReferenceError: history is not defined"
File: src/lib.rs
Location: [8,6].

    at abort (/Users/niraj/Documents/Projects/polywrap/uri-resolver-extensions/node_modules/@wraplib/pwr/node_modules/@polywrap/wasm-js/build/WasmWrapper.js:131:35)
    at __wrap_abort (/Users/niraj/Documents/Projects/polywrap/uri-resolver-extensions/node_modules/@wraplib/pwr/node_modules/@polywrap/wasm-js/build/imports.js:212:17)
    at /Users/niraj/Documents/Projects/polywrap/uri-resolver-extensions/node_modules/@polywrap/asyncify-js/build/AsyncWasmInstance.js:197:28
    at wasm://wasm/0005b816:wasm-function[56]:0xff4a
    at wasm://wasm/0005b816:wasm-function[55]:0xfcac
    at wasm://wasm/0005b816:wasm-function[98]:0x13662
    at wasm://wasm/0005b816:wasm-function[73]:0x117d7
    at wasm://wasm/0005b816:wasm-function[9]:0x2aa9
    at wasm://wasm/0005b816:wasm-function[54]:0xfa3f
    at wasm://wasm/0005b816:wasm-function[37]:0xd470
❯ npx @wraplib/pwr --version
[
  Uri {
    _config: {
      uri: 'wrap://pwr/--version',
      authority: 'pwr',
      path: '--version'
    }
  },
  Uri {
    _config: {
      uri: 'wrap://ens/--version.pwr-app.eth',
      authority: 'ens',
      path: '--version.pwr-app.eth'
    }
  }
]
Invoked
ReferenceError: history is not defined
    at CustomPolywrapClient.<anonymous> (/Users/niraj/Documents/Projects/polywrap/uri-resolver-extensions/node_modules/@wraplib/pwr/node_modules/@polywrap/client-js/build/PolywrapClient.js:585:171)
    at step (/Users/niraj/Documents/Projects/polywrap/uri-resolver-extensions/node_modules/@wraplib/pwr/node_modules/@polywrap/client-js/build/PolywrapClient.js:50:23)
    at Object.next (/Users/niraj/Documents/Projects/polywrap/uri-resolver-extensions/node_modules/@wraplib/pwr/node_modules/@polywrap/client-js/build/PolywrapClient.js:31:53)
    at fulfilled (/Users/niraj/Documents/Projects/polywrap/uri-resolver-extensions/node_modules/@wraplib/pwr/node_modules/@polywrap/client-js/build/PolywrapClient.js:22:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Niraj-Kamdar** [comment]
Solved with newest pwr release
